#!/bin/bash

#PBS -q dm
#PBS -N dem          
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ncpus=14     

# set path of wroking directory
cd $PBS_O_WORKDIR

# set number of threads     
export OMP_NUM_THREADS=14   

./demviscous   

