#!/bin/bash

#PBS -q dm
#PBS -N demelastic   
#PBS -l walltime=24:00:00
#PBS -l nodes=1:ncpus=28     
#PBS -l mem=2gb

# set path of wroking directory
cd $PBS_O_WORKDIR

# set number of threads     
export OMP_NUM_THREADS=28   

./demelastic

