#!/bin/bash

#PBS -q sm
#PBS -N drexm        
#PBS -l walltime=24:00:00
# For distributed memory machine
# PBS -l nodes=2:ppn=2:ncpus=14
# For shared memory machine
#PBS -l nodes=1:ppn=8:ncpus=14   
#PBS -l mem=200gb

# set path of wroking directory
cd $PBS_O_WORKDIR

# set number of threads     
export OMP_NUM_THREADS=14  

# mpirun -np 2 ./drex_m ../cookbooks/2Dcartesian_convection/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/2Dpolar_convection/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/2Dpolar_subduction/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/3Dcartesian_sinkingslab/drexm_input.dat
# mpirun -np 8 ./drex_m ../cookbooks/3Dspherical_sinkingslab/drexm_input.dat
# mpirun -np 16 ./drex_m ../cookbooks/3Dspherical_global/drexm_input.dat
