#!/bin/bash
# set number of threads     
export OMP_NUM_THREADS=14

 mpirun -np 2 ./drex_m ../cookbooks/2Dcartesian_convection/drexm_input.dat
 mpirun -np 8 ./drex_m ../cookbooks/2Dpolar_convection/drexm_input.dat
 mpirun -np 8 ./drex_m ../cookbooks/2Dpolar_subduction/drexm_input.dat
 mpirun -np 8 ./drex_m ../cookbooks/3Dcartesian_sinkingslab/drexm_input.dat
 mpirun -np 8 ./drex_m ../cookbooks/3Dspherical_sinkingslab/drexm_input.dat
 mpirun -np 16 ./drex_m ../cookbooks/3Dspherical_global/drexm_input.dat
