#!/bin/bash

rm *.mod
rm -r objects/

h5pfc savstack.f90 -o savstack
h5pfc sav2cijkl.f90 -o sav2cijkl
h5pfc fazi2splitstat.f90 -o fazi2splitstat

if [ ! -s objects/ ];then \
	mkdir objects/;\
fi;
    

mv *.o objects/
