#!/bin/bash

#PBS -q sm
#PBS -N sks          
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ncpus=1   
#PBS -l mem=64gb   

# set path of wroking directory
cd $PBS_O_WORKDIR

# set number of threads     
export OMP_NUM_THREADS=1 

./calc_split_from_flow_model
