#!/bin/bash

# set number of threads     
export OMP_NUM_THREADS=28 

 ./viztomo ../cookbooks/2Dcartesian_convection/viztomo_input.dat
 ./viztomo ../cookbooks/2Dpolar_convection/viztomo_input.dat
 ./viztomo ../cookbooks/2Dpolar_subduction/viztomo_input.dat
 ./viztomo ../cookbooks/2Dpolar_subduction/viztomo_input_spo.dat # to check the effect of melt-filled cracks superimposed on the LPO close to the ridge
 ./viztomo ../cookbooks/3Dcartesian_sinkingslab/viztomo_input.dat
 ./viztomo ../cookbooks/3Dspherical_sinkingslab/viztomo_input.dat
 ./viztomo ../cookbooks/3Dspherical_global/viztomo_input.dat
