#!/bin/bash

h5pfc -qopenmp -o vizvisc    \
	moduledem.f90           \
	module.f90           \
	VIZVISC.f90	     \
	read_input_file.f90  \
	lagrangian.f90       \
	eulerian.f90 	     \
	viscoustensor.f90         \
	loaddem.f90          \
	../ext_funct/dsyevc3.f \
        ../ext_funct/dsyevh3.f \
	../ext_funct/dsyevq3.f \
	../ext_funct/dsytrd3.f	      

if [ ! -s objects/ ];then \
	mkdir objects/;\
fi;
	 
mv *.o objects/
