#!/bin/bash

h5pfc -qopenmp -o vizvisc    \
	module.f90           \
	VIZVISC.f90	     \
	read_input_file.f90  \
	lagrangian.f90       \
	eulerian.f90 	     \
	loaddem.f90          \
	../EXEV/moduledem.f90 \
	../EXEV/viscoustensor.f90 \
    	../shared_funct/readfunct.f90 \
	../shared_funct/dsyevc3.f \
        ../shared_funct/dsyevh3.f \
	../shared_funct/dsyevq3.f \
	../shared_funct/dsytrd3.f	      

if [ ! -s objects/ ];then \
	mkdir objects/;\
fi;
	 
mv *.o objects/
